### DM Med Check ###
# DM Meds
meds <- read.table("Med0.txt", sep = '|', fill = TRUE, quote = "", header = T)

DM_list <- c("metformin",
             "alogliptin",
             "canagliflozin",
             "dapagliflozin",
             "empagliflozin",
             "glipizide",
             "glyburide",
             "glucovance",
             "linaglipitin",
             "Jentadueto",
             "pioglitazone",
             "actoplus",
             "synjardy",
             "xigduo",
             "invokamet",
             "kazano",
             "repaglinide",
             "prandimet",
             "rosiglitazone",
             "avandamet",
             "saxagliptin",
             "kombiglyze",
             "sitagliptin",
             "janumet",
             "alogliptin",
             "nesina",
             "kazano",
             "oseni",
             "linagliptin",
             "tradjenta",
             "empagliflozin",
             "glyxambi",
             "saxagliptin",
             "onglyza",
             "januvia",
             "juvisync",
             "albiglutide",
             "tanzeum",
             "dulaglutide",
             "trulicity",
             "exenatide",
             "byetta",
             "bydureon",
             "liraglutide",
             "victoza",
             "nateglinide",
             "starlix",
             "repaglinide",
             "prandin",
             "prandimet",
             "dapagliflozin",
             "farxiga",
             "xigduo",
             "canagliflozin",
             "invokana",
             "invokamet",
             "empagliflozin",
             "jardiance",
             "glyxambi",
             "synjardy",
             "glimepiride",
             "amaryl",
             "duetact",
             "avandaryl",
             "gliclazide",
             "glipizide",
             "glucotrol",
             "metaglip",
             "glyburide",
             "diabeta",
             "glynase",
             "micronase",
             "glucovance",
             "chlorpropamide",
             "diabinese",
             "tolazamide",
             "tolinase",
             "tolbutamide",
             "orinase",
             "tol-tab",
             "avandia",
             "avandaryl",
             "actos",
             "oseni",
             "duetact",
             "actoplus")

DM_list2 <- c("lispro",
              "lyspro",
              "humalog",
              "aspart",
              "novalog",
              "glulisine",
              "apidra",
              "insulin",
              "novolin",
              "velosulin",
              "nph",
              "glargine",
              "Basaglar",
              "Lantus",
              "Toujeo",
              "detemir",
              "levemir",
              "degludec",
              "Tresiba",
              "humulin",
              "novalin",
              "afrezza",
              "metformin",
              "alogliptin",
              "canagliflozin",
              "dapagliflozin",
              "empagliflozin",
              "glipizide",
              "glyburide",
              "glucovance",
              "linaglipitin",
              "Jentadueto",
              "pioglitazone",
              "actoplus",
              "synjardy",
              "xigduo",
              "invokamet",
              "kazano",
              "repaglinide", 
              "prandimet",
              "rosiglitazone",
              "avandamet",
              "saxagliptin", 
              "kombiglyze",
              "sitagliptin",
              "janumet",
              "alogliptin", 
              "nesina",
              "kazano",
              "oseni",
              "linagliptin",
              "tradjenta",
              "empagliflozin",
              "glyxambi",
              "saxagliptin",
              "onglyza",
              "januvia",
              "juvisync",
              "albiglutide", 
              "tanzeum",
              "dulaglutide",
              "trulicity",
              "exenatide",
              "byetta",
              "bydureon",
              "liraglutide",
              "victoza",
              "nateglinide",
              "starlix",
              "repaglinide",
              "prandin",
              "prandimet",
              "dapagliflozin",
              "farxiga",
              "xigduo",
              "canagliflozin",
              "invokana",
              "invokamet",
              "empagliflozin",
              "jardiance",
              "glyxambi",
              "synjardy",
              "glimepiride",
              "amaryl",
              "duetact",
              "avandaryl",
              "gliclazide",
              "glipizide",
              "glucotrol",
              "metaglip",
              "glyburide",
              "diabeta",
              "glynase",
              "micronase",
              "glucovance",
              "chlorpropamide",
              "diabinese",
              "tolazamide",
              "tolinase",
              "tolbutamide",
              "orinase",
              "tol-tab",
              "avandia",
              "avandaryl",
              "actos",
              "oseni",
              "duetact",
              "actoplus")

DM_meds <- subset(meds, grepl(paste(DM_list2, collapse = "|"), meds$Medication, ignore.case = T))
length(unique(DM_meds$EMPI))

dem <- read.table("Dem.txt", sep = '|', fill = TRUE, quote = "", header = T)

DM_check <- subset(dem, dem$EMPI%in%DM_meds$EMPI)

dia <- read.table("Dia0.txt", sep = '|', fill = TRUE, quote = "", header = T)
DM_dia_list <- c("diabetes")
DM_dia <- subset(dia, grepl(paste(DM_dia_list, collapse = "|"), dia$Diagnosis_Name, ignore.case = T))

med_and_dia <- subset(DM_check, DM_check$EMPI%in%DM_dia$EMPI)

write.csv(DM_check, "DM_check.csv")

### DM Script ###
lab <- read.table("Lab0.txt", sep = '|', fill = TRUE, quote = "", header = T)
hgba1c_list <- c("HEMOGLOBIN A1C", "a1c", "hgb a1c", "hba1c", "hbga1c")
hgba1c_labs <- subset(lab, grepl(paste(hgba1c_list, collapse = "|"), lab$Test_Description, ignore.case = T))

hgba1c_labs$Result <- as.character(hgba1c_labs$Result)
hgba1c_labs$Result <- as.numeric(hgba1c_labs$Result)
DM_pts <- subset(hgba1c_labs, hgba1c_labs$Result >= 6.5)

dem <- read.table("Dem.txt", sep = '|', fill = TRUE, quote = "", header = T)

DMA1C <- subset(dem, dem$EMPI%in%DM_pts$EMPI)

`%ni%`=function(x,y) !(x %in% y)
DMA1C_merge <- subset(DMA1C, DMA1C$EMPI%ni%DM_check$EMPI)
DMA1C_or_med <- rbind(DM_check, DMA1C_merge)

DMA1C_merge2 <- subset(DMA1C, DMA1C$EMPI%ni%med_and_dia$EMPI)
DMA1C_or_medAdia <- rbind(DMA1C_merge2, med_and_dia)

write.csv(DMA1C_or_medAdia, "A1C_or_med_and_dia.csv")
write.csv(DMA1C_or_med, "DM_A1Cs_or_Med.csv")